default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: github_profiles_indexer_development

test:
  <<: *default
  database: github_profiles_indexer_test
